# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
@tool
class_name LocalizationKeys

const KEY_NAME = "KEY_NAME"
const KEY_PLAY = "KEY_PLAY"
const KEY_SETTINGS = "KEY_SETTINGS"
const KEY_LANGUAGE = "KEY_LANGUAGE"
const KEY_QUIT = "KEY_QUIT"
const KEY_TITLE = "KEY_TITLE"
const KEY_HIGHSCORE = "KEY_HIGHSCORE"
const KEY_VSYNC = "KEY_VSYNC"
const KEY_FULLSCREEN = "KEY_FULLSCREEN"
const KEY_RESOLUTION = "KEY_RESOLUTION"
const KEY_HEALTH = "KEY_HEALTH"
const KEY_TIMER = "KEY_TIMER"
const KEY_SCORE = "KEY_SCORE"
const KEY_HOWTO = "KEY_HOWTO"
const KEY_SPDU = "KEY_SPDU"
const DESC_SPDU = "DESC_SPDU"
const KEY_SPDURLD = "KEY_SPDURLD"
const DESC_SPDURLD = "DESC_SPDURLD"
const KEY_SPDUJFD = "KEY_SPDUJFD"
const DESC_SPDUJFD = "DESC_SPDUJFD"
const KEY_RLU = "KEY_RLU"
const DESC_RLU = "DESC_RLU"
const KEY_RLD = "KEY_RLD"
const DESC_RLD = "DESC_RLD"
const KEY_RLUSPDD = "KEY_RLUSPDD"
const DESC_RLUSPDD = "DESC_RLUSPDD"
const KEY_PHU = "KEY_PHU"
const DESC_PHU = "DESC_PHU"
const KEY_TR = "KEY_TR"
const DESC_TR = "DESC_TR"
const KEY_MSPDU = "KEY_MSPDU"
const DESC_MSPDU = "DESC_MSPDU"
const KEY_MRLU = "KEY_MRLU"
const DESC_MRLU = "DESC_MRLU"
const KEY_MPHU = "KEY_MPHU"
const DESC_MPHU = "DESC_MPHU"
const KEY_JFUSPDD = "KEY_JFUSPDD"
const DESC_JFUSPDD = "DESC_JFUSPDD"
const KEY_JFUOSPDU = "KEY_JFUOSPDU"
const DESC_JFUOSPDU = "DESC_JFUOSPDU"
const KEY_MJFU = "KEY_MJFU"
const DESC_MJFU = "DESC_MJFU"
const KEY_JPU = "KEY_JPU"
const DESC_JPU = "DESC_JPU"
const KEY_FU = "KEY_FU"
const DESC_FU = "DESC_FU"
const KEY_FUSPDD = "KEY_FUSPDD"
const DESC_FUSPDD = "DESC_FUSPDD"
const KEY_FURLD = "KEY_FURLD"
const DESC_FURLD = "DESC_FURLD"
const KEY_FUJFD = "KEY_FUJFD"
const DESC_FUJFD = "DESC_FUJFD"
const KEY_MFU = "KEY_MFU"
const DESC_MFU = "DESC_MFU"
const KEY_MFD = "KEY_MFD"
const DESC_MFD = "DESC_MFD"
const KEY_SPDUFD = "KEY_SPDUFD"
const DESC_SPDUFD = "DESC_SPDUFD"
const KEY_RLUFD = "KEY_RLUFD"
const DESC_RLUFD = "DESC_RLUFD"
const KEY_JFUFD = "KEY_JFUFD"
const DESC_JFUFD = "DESC_JFUFD"
const KEY_BACK = "KEY_BACK"
const KEY_CONT = "KEY_CONT"
const KEY_KEYBOARD_CONT = "KEY_KEYBOARD_CONT"
const KEY_CONTROLLER_CONT = "KEY_CONTROLLER_CONT"
const KEY_GOAL = "KEY_GOAL"
const KEY_GOAL_PT1 = "KEY_GOAL_PT1"
const KEY_GOAL_PT2 = "KEY_GOAL_PT2"
const KEY_PAUSE = "KEY_PAUSE"
const KEY_RESUME = "KEY_RESUME"
const KEY_GIVEUP = "KEY_GIVEUP"
const KEY_STAT_PSPD3D = "KEY_STAT_PSPD3D"
const KEY_STAT_PSPD2D = "KEY_STAT_PSPD2D"
const KEY_STAT_ABS = "KEY_STAT_ABS"
const KEY_STAT_ESPD3D = "KEY_STAT_ESPD3D"
const KEY_STAT_ESPD2D = "KEY_STAT_ESPD2D"
const KEY_STAT_RL = "KEY_STAT_RL"
const KEY_SKIP_K = "KEY_SKIP_K"
const KEY_FROM_SCORE = "KEY_FROM_SCORE"
const KEY_SKIP_C = "KEY_SKIP_C"
const KEY_SKIP_F = "KEY_SKIP_F"

const KEYS = [
 "KEY_NAME",
 "KEY_PLAY",
 "KEY_SETTINGS",
 "KEY_LANGUAGE",
 "KEY_QUIT",
 "KEY_TITLE",
 "KEY_HIGHSCORE",
 "KEY_VSYNC",
 "KEY_FULLSCREEN",
 "KEY_RESOLUTION",
 "KEY_HEALTH",
 "KEY_TIMER",
 "KEY_SCORE",
 "KEY_HOWTO",
 "KEY_SPDU",
 "DESC_SPDU",
 "KEY_SPDURLD",
 "DESC_SPDURLD",
 "KEY_SPDUJFD",
 "DESC_SPDUJFD",
 "KEY_RLU",
 "DESC_RLU",
 "KEY_RLD",
 "DESC_RLD",
 "KEY_RLUSPDD",
 "DESC_RLUSPDD",
 "KEY_PHU",
 "DESC_PHU",
 "KEY_TR",
 "DESC_TR",
 "KEY_MSPDU",
 "DESC_MSPDU",
 "KEY_MRLU",
 "DESC_MRLU",
 "KEY_MPHU",
 "DESC_MPHU",
 "KEY_JFUSPDD",
 "DESC_JFUSPDD",
 "KEY_JFUOSPDU",
 "DESC_JFUOSPDU",
 "KEY_MJFU",
 "DESC_MJFU",
 "KEY_JPU",
 "DESC_JPU",
 "KEY_FU",
 "DESC_FU",
 "KEY_FUSPDD",
 "DESC_FUSPDD",
 "KEY_FURLD",
 "DESC_FURLD",
 "KEY_FUJFD",
 "DESC_FUJFD",
 "KEY_MFU",
 "DESC_MFU",
 "KEY_MFD",
 "DESC_MFD",
 "KEY_SPDUFD",
 "DESC_SPDUFD",
 "KEY_RLUFD",
 "DESC_RLUFD",
 "KEY_JFUFD",
 "DESC_JFUFD",
 "KEY_BACK",
 "KEY_CONT",
 "KEY_KEYBOARD_CONT",
 "KEY_CONTROLLER_CONT",
 "KEY_GOAL",
 "KEY_GOAL_PT1",
 "KEY_GOAL_PT2",
 "KEY_PAUSE",
 "KEY_RESUME",
 "KEY_GIVEUP",
 "KEY_STAT_PSPD3D",
 "KEY_STAT_PSPD2D",
 "KEY_STAT_ABS",
 "KEY_STAT_ESPD3D",
 "KEY_STAT_ESPD2D",
 "KEY_STAT_RL",
 "KEY_SKIP_K",
 "KEY_FROM_SCORE",
 "KEY_SKIP_C",
 "KEY_SKIP_F"
]
